-- ============================================================
--  SchartenGuessr — Supabase schema (own leaderboard)
--  Run this once in the Supabase SQL editor of the project that
--  backs SchartenGuessr (same project/keys as Ternberg & Wels).
--
--  The tables `players` and `achievements` are SHARED across all
--  Guessr sites and already exist — they are NOT recreated here.
--  Only the Scharten-prefixed tables + RPC are added below.
-- ============================================================

-- 1) All-time scores -----------------------------------------
create table if not exists public.scharten_scores (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  score       integer     not null,
  created_at  timestamptz not null default now()
);
create index if not exists scharten_scores_score_idx on public.scharten_scores (score desc);
create index if not exists scharten_scores_name_idx  on public.scharten_scores (lower(name));

-- 2) Daily-challenge scores ----------------------------------
create table if not exists public.scharten_daily_scores (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  score       integer     not null,
  date_key    text        not null,
  device_id   text,
  created_at  timestamptz not null default now()
);
create index if not exists scharten_daily_scores_date_idx
  on public.scharten_daily_scores (date_key, score desc);
-- one entry per device per day (best score kept by the RPC below)
create unique index if not exists scharten_daily_scores_device_uniq
  on public.scharten_daily_scores (date_key, device_id)
  where device_id is not null;

-- 3) Daily guesses (heatmap) ---------------------------------
create table if not exists public.scharten_daily_guesses (
  id           bigint generated by default as identity primary key,
  date_key     text,
  location_id  text,
  guess_lat    double precision,
  guess_lng    double precision,
  player_name  text,
  created_at   timestamptz not null default now()
);
create index if not exists scharten_daily_guesses_loc_idx
  on public.scharten_daily_guesses (location_id);

-- 4) Changelog ("Was ist neu?") ------------------------------
create table if not exists public.scharten_changelog_entries (
  id       bigint generated by default as identity primary key,
  date     date,
  version  text,
  icon     text,
  title    text not null,
  body     text,
  image    text
);

-- 5) Daily-score upsert RPC (keeps best score per device/day) -
create or replace function public.submit_scharten_daily_score(
  p_name text, p_score integer, p_date_key text, p_device_id text
) returns void
language plpgsql
security definer
as $func$
begin
  insert into public.scharten_daily_scores (name, score, date_key, device_id)
  values (p_name, p_score, p_date_key, p_device_id)
  on conflict (date_key, device_id) where device_id is not null
  do update
     set score      = excluded.score,
         name       = excluded.name,
         created_at = now()
   where excluded.score > public.scharten_daily_scores.score;
end;
$func$;

-- 6) Row Level Security --------------------------------------
--    The app uses the anon key for all reads/writes (incl. the
--    admin panel), mirroring the existing Ternberg/Wels setup.
alter table public.scharten_scores            enable row level security;
alter table public.scharten_daily_scores      enable row level security;
alter table public.scharten_daily_guesses     enable row level security;
alter table public.scharten_changelog_entries enable row level security;

do $policies$
declare t text;
begin
  foreach t in array array[
    'scharten_scores','scharten_daily_scores',
    'scharten_daily_guesses','scharten_changelog_entries'
  ] loop
    execute format('drop policy if exists %1$s_all on public.%1$s;', t);
    execute format(
      'create policy %1$s_all on public.%1$s for all to anon, authenticated using (true) with check (true);',
      t);
  end loop;
end
$policies$;

grant usage on schema public to anon, authenticated;
grant all on
  public.scharten_scores,
  public.scharten_daily_scores,
  public.scharten_daily_guesses,
  public.scharten_changelog_entries
  to anon, authenticated;
grant execute on function public.submit_scharten_daily_score(text, integer, text, text)
  to anon, authenticated;
